# Autogenerated with SMOP 0.32-7-gcce8558
from smop.core import *
from matplotlib.pyplot import *
from numpy import *

# 

' DIGITALNI FILTRI'
'-------------------------------------------------------------------'
# filtriranje v frekvennem prostoru
close_('all')
clc
Fsamp=1024
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:5

LomnaFrek=50
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:6

figure
x=randn(1,dot(1,Fsamp))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:9

X=fft.fft(x)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:10

F=matlabarray(cat(ones(1,LomnaFrek),zeros(1,length(x) - dot(2,LomnaFrek) + 1),ones(1,LomnaFrek - 1)))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:11

subplot(2,1,1)
hold('on')
plot(abs(X) / max(abs(ravel(X))))

plot(F,'r',lineWidth=2)

xlabel('f (Hz)')
ylabel('amplituda')
title(cat('Lomna frekvenca = ',num2str(LomnaFrek),' Hz'))
axis('tight')
R=multiply(X,F)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:19

r=fft.fft.ifft(R)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:20

subplot(2,1,2)
hold('on')
plot(x)

plot(r,'r',lineWidth=2)

xlabel('t (vzorci)')
ylabel('amplituda')
axis('tight')
'-------------------------------------------------------------------'
########################################
# impulzni odziv filtra - antivzronost, dolina filtra, konvolucija v asovni domeni...
close_('all')
clc
Fsamp=1024
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:31

LomnaFrek=50
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:32

F=matlabarray(cat(ones(1,LomnaFrek),zeros(1,Fsamp - dot(2,LomnaFrek) + 1),ones(1,LomnaFrek - 1)))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:33

f=fft.fft.ifftshift(fft.fft.ifft(F))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:35

# asovno os prestravimo za length(F)/2 vzorcev v levo.

figure
subplot(3,1,1)
plot(cat(arange(- length(f) / 2,length(f) / 2 - 1)),f)
xlabel('t (vzorci)')
ylabel('amplituda')
axis('tight')
title(cat('impulzni odziv frekvennega filtra z Lomno frekvenco = ',num2str(LomnaFrek),' Hz'))
subplot(3,1,2)
plot(cat(arange(- length(f) / 2,length(f) / 2 - 1)),abs(f))
xlabel('t (vzorci)')
ylabel('amplituda')
title('absolutna vrednost impulznega odziva frekvennega filtra')
#set(gca,'YScale','log');
axis('tight')
subplot(3,1,3)
plot(cat(arange(- length(f) / 2,length(f) / 2 - 1)),dot(20,log10(abs(f))))
xlabel('t (vzorci)')
ylabel('amplituda (dB)')
title('absolutna vrednost impulznega odziva frekvennega filtra')
axis('tight')
#####################################
# poskusimo narediti filter konen in vzroen
# impulzni odziv se e nahaja v spr. impulzni
LomnaFrek=200
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:59
Fsamp=1024
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:60

F=matlabarray(cat(ones(1,LomnaFrek),zeros(1,Fsamp - dot(2,LomnaFrek) + 1),ones(1,LomnaFrek - 1)))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:61

f=fft.fft.ifftshift(fft.fft.ifft(F))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:62

# asovno os prestravimo za length(F)/2 vzorcev v levo.
f2=copy(f)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:64
f2[512:1024]=f2[512 - 20:1024 - 20]
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:65

f2[1:511]=0
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:66

f2[512 + 100:1024]=0
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:67

F2=fft.fft(f2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:68

close_('all')
clc
figure
subplot(3,1,1)
hold('on')
plot(cat(arange(- length(f2) / 2,length(f2) / 2 - 1)),f2,'r')
plot(cat(arange(- length(f) / 2,length(f) / 2 - 1)),f,'b')
xlabel('t (vzorci)')
ylabel('amplituda')
axis('tight')
title(cat('impulzni odziv frekvennega filtra z Lomno frekvenco = ',num2str(LomnaFrek),' Hz'))
subplot(3,1,2)
hold('on')
plot(cat(arange(- length(f2) / 2,length(f2) / 2 - 1)),dot(20,log10(abs(f2))),'r')
plot(cat(arange(- length(f) / 2,length(f) / 2 - 1)),dot(20,log10(abs(f))))
xlabel('t (vzorci)')
ylabel('amplituda (dB)')
title('absolutna vrednost frekvenne karakteristike filtra')
axis('tight')
subplot(3,1,3)
hold('on')
plot(abs(F))
plot(abs(F2),'r')
xlabel('f (Hz)')
ylabel('amplituda')
title('absolutna vrednost frekvenne karakteristike filtra')
#set(gca,'YScale','log');
axis('tight')
#####################################
# animacija premika impulz. odziva filtra v desno
LomnaFrek=200
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:95
Fsamp=1024
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:96

F=matlabarray(cat(ones(1,LomnaFrek),zeros(1,Fsamp - dot(2,LomnaFrek) + 1),ones(1,LomnaFrek - 1)))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:97

f=fft.fft.ifftshift(fft.fft.ifft(F))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:98

# asovno os prestravimo za length(F)/2 vzorcev v levo.

close_('all')
clc
figure
for dt in arange(0,200,5).reshape(-1):
    dRepL=100
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:104
    dRepD=100
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:105
    f2=copy(f)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:106
    f2[512 - dRepL:1024]=f2[512 - dt - dRepL:1024 - dt]
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:107
    f2[1:511 + dt - dRepL]=0
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:108
    f2[512 + dt + dRepD:1024]=0
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:109
    F2=fft.fft(f2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:110
    subplot(3,1,1)
    clf()
    hold('on')
    plot(cat(arange(- length(f) / 2,length(f) / 2 - 1)),f,'b')
    plot(cat(arange(- length(f2) / 2,length(f2) / 2 - 1)),f2,'r')
    xlabel('t (vzorci)')
    ylabel('amplituda')
    axis('tight')
    title(cat('impulzni odziv frekvennega filtra z Lomno frekvenco = ',num2str(LomnaFrek),' Hz'))
    subplot(3,1,2)
    clf()
    hold('on')
    plot(abs(F))
    plot(abs(F2),'r')
    xlabel('f (Hz)')
    ylabel('amplituda')
    title('absolutna vrednost FFT')
    axis('tight')
    subplot(3,1,3)
    clf()
    hold('on')
    plot(unwrap(atan2(imag(F),real(F))),lineWidth=2)
    plot(unwrap(atan2(imag(F2),real(F2))),'r')
    xlabel('f (Hz)')
    ylabel('faza')
    title('faza FFT')
    axis('tight')
    #set(gca,'YLim',cat(0,2500))
    autoscale(False)
    ylim(0,2500)
    pause(0.5)

#####################################
# animacija doline impulz. odziva filtra - Gibbsov effekt
LomnaFrek=200
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:140
Fsamp=1024
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:141

F=matlabarray(cat(ones(1,LomnaFrek),zeros(1,Fsamp - dot(2,LomnaFrek) + 1),ones(1,LomnaFrek - 1)))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:142

f=fft.fft.ifftshift(fft.fft.ifft(F))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:143

# asovno os prestravimo za length(F)/2 vzorcev v levo.

close_('all')
clc
figure
dt=100
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:148

for dRepL in arange(100,10,- 5).reshape(-1):
    dRepD=copy(dRepL)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:151
    f2=copy(f)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:152
    f2[512 - dRepL:1024]=f2[512 - dt - dRepL:1024 - dt]
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:153
    f2[1:511 + dt - dRepL]=0
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:154
    f2[512 + dt + dRepD:1024]=0
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:155
    F2=fft.fft(f2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:156
    subplot(3,1,1)
    clf()
    hold('on')
    plot(cat(arange(- length(f) / 2,length(f) / 2 - 1)),f,'b')
    plot(cat(arange(- length(f2) / 2,length(f2) / 2 - 1)),f2,'r')
    xlabel('t (vzorci)')
    ylabel('amplituda')
    axis('tight')
    title(cat('impulzni odziv frekvennega filtra z Lomno frekvenco = ',num2str(LomnaFrek),' Hz, dolina filtra = ',num2str(dRepD + dRepL),' vzorcev'))
    subplot(3,1,2)
    clf()
    hold('on')
    plot(abs(F))
    plot(abs(F2),'r')
    xlabel('f (Hz)')
    ylabel('amplituda')
    title('absolutna vrednost FFT')
    axis('tight')
    subplot(3,1,3)
    clf()
    hold('on')
    plot(unwrap(atan2(imag(F),real(F))),lineWidth=2)
    plot(unwrap(atan2(imag(F2),real(F2))),'r')
    xlabel('f (Hz)')
    ylabel('faza')
    title('faza FFT')
    axis('tight')
    set(gca,'YLim',cat(0,2500))
    pause(2)

'-------------------------------------------------------------------'
#####################################
# tekoe povpreje

close_('all')
clc
clear('y')
fsamp=1024
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:189

x=randn(1,dot(1,fsamp))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:190

m=2
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:191

for n in arange(m,length(x)).reshape(-1):
    y[n]=sum(x[n - m + 1:n])
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:193

X=fft.fft(x)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:195

Y=fft.fft(y)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:196

close_('all')
clc
figure
subplot(2,1,1)
hold('on')
plot(x)

plot(y,'r',lineWidth=2)

xlabel('t (vzorci)')
ylabel('amplituda')
axis('tight')
title(cat('Tekoe povpreje, m = ',num2str(m)))
subplot(2,1,2)
hold('on')
plot(abs(X))

plot(abs(Y),'r',lineWidth=2)

xlabel('f (Hz)')
ylabel('amplituda')
title(cat('absolutna vrednost FFT'))
axis('tight')
########################################################
# animacija pri razlinih redih fitra m
close_('all')
clc
clear('y')
fsamp=1024
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:219

x=randn(1,dot(1,fsamp))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:220

X=fft.fft(x)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:221

figure
for m in cat(arange(1,4),arange(5,100,5)).reshape(-1):
    for n in arange(m,length(x)).reshape(-1):
        y[n]=mean(x[n - m + 1:n])
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:226
    Y=fft.fft(y)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:228
    subplot(2,1,1)
    clf()
    hold('on')
    plot(x)
    plot(y,'r',lineWidth=2)
    xlabel('t (vzorci)')
    ylabel('amplituda')
    axis('tight')
    title(cat('Tekoe povpreje, m = ',num2str(m)))
    subplot(2,1,2)
    clf()
    hold('on')
    plot(abs(X))
    plot(abs(Y),'r',lineWidth=2)
    xlabel('f (Hz)')
    ylabel('amplituda')
    title(cat('absolutna vrednost FFT'))
    axis('tight')
    pause(1)

#############################################
# frekvenna karakteristika tekoega povpreja
close_('all')
clc
figure
for m in cat(arange(1,4),arange(5,20,5)).reshape(-1):
    subplot(2,1,1)
    clf()
    hold('on')
    f=matlabarray(cat(ones(1,m),zeros(1,length(x) - m)))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:253
    F=fft.fft(f)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:254
    plot(abs(F),'m',lineWidth=2)
    xlabel('f (Hz)')
    ylabel('amplituda')
    title(cat('absolutna vrednost FFT, povpreje preko, m = ',num2str(m)))
    axis('tight')
    subplot(2,1,2)
    clf()
    hold('on')
    plot(unwrap(atan2(imag(F),real(F))),lineWidth=2)
    xlabel('f (Hz)')
    ylabel('faza')
    title('faza FFT')
    axis('tight')
    pause()

'------------------------------------------------------------------------------------------------------'
# NARTOVANJE FILTROV V MATLABU
#    * butter   - Butterworth filter  no gain ripple in pass band and stop band, slow cutoff
#    * cheby1   - Chebyshev filter (Type I)  no gain ripple in stop band, moderate cutoff
#    * cheby2   - Chebyshev filter (Type II)  no gain ripple in pass band, moderate cutoff
#    * ellip    - Elliptic filter  gain ripple in pass and stop band, fast cutoff
#    * besself  - Bessel filter  no group delay ripple, no gain ripple in both bands, slow gain cutoff
'-------------------------------------------------------------------------------------------------------'

clear
clc
filter_order=5
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:281

Rp=0.5
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:282

Rp2=20
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:283

Rs=20
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:284

Wn=100 / 500
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:285

f=matlabarray(cat(0,0.2,0.2,1))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:286

m=matlabarray(cat(1,1,0,0))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:287

subplot(2,2,1)
hold('on')
b,a=cheby1(filter_order,Rp,Wn,'low',nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:290

h,w=freqz(b,a,128,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:291

plot(f,m,lineWidth=2)
plot(w / pi,abs(h),'r',lineWidth=2)
axis('tight')
legend('idealni','nartovan')
xlabel('2*f/f_{vzorevalna}','FontSize',12)
ylabel('amplituda','FontSize',12)
title(cat('Chebyshev filter (Tip 1): red =',num2str(filter_order)),'FontSize',12)
subplot(2,2,2)
hold('on')
b,a=cheby2(filter_order,Rp2,Wn,'low',nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:301

h,w=freqz(b,a,128,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:302

plot(f,m,lineWidth=2)
plot(w / pi,abs(h),'r',lineWidth=2)
axis('tight')
legend('idealni','nartovan')
xlabel('2*f/f_{vzorevalna}','FontSize',12)
ylabel('amplituda','FontSize',12)
title(cat('Chebyshev filter (Tip 2): red =',num2str(filter_order)),'FontSize',12)
subplot(2,2,3)
hold('on')
b,a=butter(filter_order,Wn,'low',nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:312

h,w=freqz(b,a,128,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:313

plot(f,m,lineWidth=2)
plot(w / pi,abs(h),'r',lineWidth=2)
axis('tight')
legend('idealni','nartovan')
xlabel('2*f/f_{vzorevalna}','FontSize',12)
ylabel('amplituda','FontSize',12)
title(cat('Butterworth filter: red =',num2str(filter_order)),'FontSize',12)
subplot(2,2,4)
hold('on')
b,a=ellip(filter_order,Rp,Rs,Wn,'low',nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:323

h,w=freqz(b,a,128,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:324

plot(f,m,lineWidth=2)
plot(w / pi,abs(h),'r',lineWidth=2)
axis('tight')
legend('idealni','nartovan')
xlabel('2*f/f_{vzorevalna}','FontSize',12)
ylabel('amplituda','FontSize',12)
title(cat('Elliptic filter: red =',num2str(filter_order)),'FontSize',12)
#####################################
# POZOR! POZOR! POZOR! POZOR! POZOR!

# pri pasovno-prepustnih in pasovno-zapornih filtrih generirajo funkcije
#    [b,a] = cheby1(filter_order,Rp,Wn)
#    [b,a] = cheby2(filter_order,Rp,Wn)
#    [b,a] = butter(filter_order,Wn)
# filtre reda 2*filter_order !!!
# glej help cheby1, help cheby2, help butter
#####################################

#####################################
# CHEBYSHEV FILTER TIPA 1 - no gain ripple in stop band, moderate cutoff
filter_order=3
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:347

Rp=0.5
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:348

Wn=cat(100,200) / 500
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:349

b,a=cheby1(filter_order,Rp,Wn,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:350

fvtool(b,a)


figure
h,w=freqz(b,a,128,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:354

plot(w / pi,abs(h),lineWidth=2)
axis('tight')
legend('konstruiran filter')
xlabel('2*f/f_{vzorevalna}','FontSize',14)
ylabel('amplituda','FontSize',14)
title(cat('absolutna vrednost frekvennega odziva, red filtra = ',num2str(filter_order)))
originalni_signal=randn(1000,1)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:362
filtriran_signal=filter(b,a,originalni_signal)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:363

figure
subplot(2,1,1)
plot(originalni_signal)
axis('tight')
xlabel('vzorci')
ylabel('amplituda')
title('originalni signal')
subplot(2,1,2)
plot(ravel(filtriran_signal),'r')
axis('tight')
xlabel('vzorci')
ylabel('amplituda')
title('filtriran signal')
# CHEBYSHEV FILTER TIPA 2   no gain ripple in pass band, moderate cutoff
filter_order=10
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:371

Rp2=100
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:372

Wn=cat(100,200) / 500
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:373

b,a=cheby2(filter_order,Rp2,Wn,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:374

fvtool(b,a)

figure
h,w=freqz(b,a,128,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:378

plot(w / pi,abs(h),lineWidth=2)
axis('tight')
legend('konstruiran filter')
xlabel('2*f/f_{vzorevalna}','FontSize',14)
ylabel('amplituda','FontSize',14)
title(cat('absolutna vrednost frekvennega odziva, red filtra = ',num2str(filter_order)))
originalni_signal=randn(1000,1)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:386
filtriran_signal=filter(b,a,originalni_signal)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:387

figure
subplot(2,1,1)
plot(originalni_signal)
axis('tight')
xlabel('vzorci')
ylabel('amplituda')
title('originalni signal')
subplot(2,1,2)
plot(filtriran_signal,'r')
axis('tight')
xlabel('vzorci')
ylabel('amplituda')
title('filtriran signal')
#####################################
# BUTTERWORTH FILTER -  no gain ripple in pass band and stop band, slow cutoff
filter_order=5
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:396

Wn=cat(100,200) / 500
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:397

b,a=butter(filter_order,Wn,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:398

fvtool(b,a)

figure
h,w=freqz(b,a,128,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:402

plot(w / pi,abs(h),lineWidth=2)
axis('tight')
legend('konstruiran filter')
xlabel('2*f/f_{vzorevalna}','FontSize',14)
ylabel('amplituda','FontSize',14)
title(cat('absolutna vrednost frekvennega odziva, red filtra = ',num2str(filter_order)))
originalni_signal=randn(10000,1)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:410
filtriran_signal=filter(b,a,originalni_signal)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:411

figure
subplot(2,1,1)
plot(originalni_signal)
axis('tight')
xlabel('vzorci')
ylabel('amplituda')
title('originalni signal')
subplot(2,1,2)
plot(filtriran_signal,'r')
axis('tight')
xlabel('vzorci')
ylabel('amplituda')
title('filtriran signal')
'-------------------------------------------------------------------'
#####################################
# FIRLS FILTER - nartovanje FIR filtra s pomojo metode najmanjih kvadratinih pogrekov (least-squares error minimization).
close_('all')
clc
filter_order=25
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:422
f=matlabarray(cat(0,0.3,0.4,0.6,0.7,1))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:423

m=matlabarray(cat(0,1,0,0,0.5,0.5))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:424

b=firls(filter_order,f,m)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:425

a=1
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:426

fvtool(b,a)
figure
h,w=freqz(b,a,128,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:431

plot(f,m,w / pi,abs(h),lineWidth=2)
axis('tight')
legend('Idealni','nartovan z metodo firls')
xlabel('2*f/f_{vzorevalna}','FontSize',14)
ylabel('amplituda','FontSize',14)
title(cat('Primerjava absolutnih vrednosti frekvennega odziva, red filtra = ',num2str(filter_order)))
y,t=impz(b,a,101,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:439

figure
stem(t,y)

axis('tight')
title('Impulzni odziv filtra')
xlabel('as (vzorci)')
ylabel('amplituda')
fvtool(b,a)

originalni_signal=randn(1000,1)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:447
filtriran_signal=filter(b,a,originalni_signal)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:448

figure
subplot(2,1,1)
plot(originalni_signal)
axis('tight')
xlabel('vzorci')
ylabel('amplituda')
title('originalni signal')
subplot(2,1,2)
plot(filtriran_signal,'r')
axis('tight')
xlabel('vzorci')
ylabel('amplituda')
title('filtriran signal')
#####################################
# # Yule-Walker FILTER - rekurzivna metoda najmanjih kvadratinih pogrekov (recursive least-squares fit to a specified frequency response)
# close all; clc;
# filter_order = 10;
# m = [0   0   1   1   0   0   1   1   0 0];
# f = [0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 1];
# [b,a] = yulewalk(filter_order,f,m);
# 
# figure;
# [h,w] = freqz(b,a,128); # izris frekvennih karakteristik filtra
# plot(f,m,w/pi,abs(h),'LineWidth',2);
# axis tight;
# legend('Idealni','nartovan z metodo yulewalk');
# xlabel('2*f/f_{vzorevalna}','FontSize',14); 
# ylabel('amplituda','FontSize',14);
# title(['Primerjava absolutnih vrednosti frekvennega odziva, red filtra = ' num2str(filter_order)]);
# 
# fvtool(b,a); # orodje za preuevanje karakteristik filtra
# 
# originalni_signal = randn(1000,1);
# filtriran_signal = filter(b,a,originalni_signal); # filtriramo signal "originalni_signal"
# figure; subplot(2,1,1);
# plot(originalni_signal); axis tight; xlabel('vzorci'); ylabel('amplituda'); title('originalni signal');
# subplot(2,1,2);
# plot(filtriran_signal,'r'); axis tight; xlabel('vzorci');
# ylabel('amplituda'); title('filtriran signal');

'-------------------------------------------------------------------'
#####################################

# P R A K T I  N I      P R I M E R I

##################################################################################################
'-------------------------------------------------------------------'
########################################################
# elektrina kitara (https://ccrma.stanford.edu/~jos/waveguide/Sound_Examples.html)
sig,Fs,nbits=wavread('ElectricGuitar.wav',nargout=3)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:491
#[sig, Fs, nbits] = wavread('gtr-dist-yes.wav');
sig=sig[:,1]
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:493

disp(cat('Vzorevalna frekvenca: ',num2str(Fs),' Hz'))
disp(cat('Loljivost: ',num2str(nbits),' bitov'))
wavplay(sig,Fs,'sync')
close_('all')
clc
tT=1024
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:499
tN=1024
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:499
dT=tT / 2
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:499
TFD,F,T=specgram(sig,tN,Fs,window(hamming,tT),dT,nargout=3)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:500
imagesc(T,F[1:128] / 1000,abs(TFD[1:128,:]))
axis('xy')
xlabel('as (s)')
ylabel('f (kHz)')
axis('tight')
title(cat('originalni signal (asovno-frekvenna ravnina)'))
# nartovanje filtra
filter_order=10
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:507
m=matlabarray(cat(1,1,0,0,0,0,0,0,0,0))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:508

f=matlabarray(cat(0,0.01,0.02,0.3,0.4,0.5,0.6,0.7,0.8,1))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:509
# m = [0   0   1   1   1   1   1   1   1   1];  # visoko-prepustno sito
# f = [0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 1];

# Yule-Walker FILTER
b,a=yulewalk(filter_order,f,m,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:514
# FIRLS FILTER
# b = firls(filter_order,f,m); # izraunamo koeficiente b
# a = 1; # firls ne vraa koeficientov a, torej nastavimo a(1) na 1

# izris frekvenne karakteristike filtra
figure
h,w=freqz(b,a,128,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:521

plot(dot(f,Fs) / 2000,m,dot(w / pi,Fs) / 2000,abs(h),lineWidth=2)
axis('tight')
legend('Idealni','Implementirani')
xlabel('f (kHz)','FontSize',14)
ylabel('amplituda','FontSize',14)
title(cat('Primerjava absolutnih vrednosti frekvennega odziva, red filtra = ',num2str(filter_order)))
fvtool(b,a)

# filtriramo signal
filt_sig=filter(b,a,sig)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:532
# nariemo TFD transformiranko
tT=1024
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:535
tN=1024
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:535
dT=tT / 2
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:535
figure
subplot(1,2,1)
TFD,F,T=specgram(sig,tN,Fs,window(hamming,tT),dT,nargout=3)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:537
imagesc(T,F[1:128] / 1000,abs(TFD[1:128,:]))
axis('xy')
xlabel('as (s)')
ylabel('f (kHz)')
axis('tight')
title(cat('Originalni signal'))
subplot(1,2,2)

TFD,F,T=specgram(filt_sig,tN,Fs,window(hamming,tT),dT,nargout=3)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:543
imagesc(T,F[1:128] / 1000,abs(TFD[1:128,:]))
axis('xy')
xlabel('as (s)')
ylabel('f (kHz)')
axis('tight')
title(cat('Filtrirani signal'))
# predvajajmo originalni in filtrirani signal
wavplay(dot(4,filt_sig),Fs,'sync')
wavplay(dot(1,sig),Fs,'sync')
# nariemo originalni in filtrirani signal
figure
hold('on')
plot(sig)
plot(filt_sig,'r')
title(cat('Opazujte zamik med originalnim in filtriranim signalom pri filtru reda ',num2str(filter_order)))
axis('tight')
# namesto funkcije filter uprabimo funkcijo filtfilt
filtfilt_sig=filtfilt(b,a,sig)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:561
figure
hold('on')
plot(sig)
plot(filtfilt_sig,'g',lineWidth=2)
title(cat('filtfilt: je e vedno zamik med originalnim in filtriranim signalom? Red filtra = ',num2str(filter_order)))
axis('tight')
wavplay(dot(1,filtfilt_sig),Fs,'sync')
wavplay(dot(1,filt_sig),Fs,'sync')
'-----------------------------------------------------------------------------------------------'
########################################################
# Linearnost faze

clear
close_('all')
clc
# FIRLS FILTER
filter_order=30
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:578
m=matlabarray(cat(0,0,1,1,0,0))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:579
f=matlabarray(cat(0,0.2,0.2,0.4,0.4,1))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:580
b1,a1=firls(filter_order,f,m,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:581
fvtool(b1,a1)
# izris frekvenne karakteristike filtra
figure
h,w=freqz(b1,a1,128,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:586

plot(f,m,w / pi,abs(h),lineWidth=2)
axis('tight')
legend('Idealni','Implementirani')
xlabel('f (kHz)','FontSize',14)
ylabel('amplituda','FontSize',14)
title(cat('Primerjava absolutnih vrednosti frekvennega odziva, red filtra = ',num2str(filter_order)))
# end of FIRLS

# CHEBYSHEV FILTER TIPA 1   no gain ripple in stop band, moderate cutoff
filter_order=10
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:596

Rp1=0.5
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:597

Wn=cat(100,200) / 500
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:598

b2,a2=cheby1(filter_order,Rp1,Wn,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:599

fvtool(b2,a2)

# izris frekvenne karakteristike filtra
figure
h,w=freqz(b2,a2,128,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:604

plot(f,m,w / pi,abs(h),lineWidth=2)
axis('tight')
legend('Idealni','Implementirani')
xlabel('f (kHz)','FontSize',14)
ylabel('amplituda','FontSize',14)
title(cat('Primerjava absolutnih vrednosti frekvennega odziva, red filtra = ',num2str(filter_order)))
# end of CHEBYSHEV FILTER TIPA 1

# BUTTERWORTH FILTER -  no gain ripple in pass band and stop band, slow cutoff
filter_order=10
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:614

Wn=cat(100,200) / 500
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:615

b3,a3=butter(filter_order,Wn,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:616

fvtool(b3,a3)

# izris frekvenne karakteristike filtra
figure
h,w=freqz(b3,a3,128,nargout=2)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:621

plot(f,m,w / pi,abs(h),lineWidth=2)
axis('tight')
legend('Idealni','Implementirani')
xlabel('f (kHz)','FontSize',14)
ylabel('amplituda','FontSize',14)
title(cat('Primerjava absolutnih vrednosti frekvennega odziva, red filtra = ',num2str(filter_order)))
# end of BUTTERWORTH FILTER

# mexican hat
t=arange(- 10,10,0.5)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:631
mh=multiply(exp((- t ** 2) / 2),(1 - t ** 2))
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:632

sig=zeros(1,1024)
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:633
sig[200:200 + length(mh) - 1]=mh
# /media/martin/2ACC5A8FCC5A54E3/ukazi5.m:634

figure
subplot(2,2,1)
plot(sig)
axis('tight')
title('originalni signal')
subplot(2,2,2)
plot(filter(b1,a1,sig))
axis('tight')
title('filtriran signal (firls)')
subplot(2,2,3)
plot(filter(b2,a2,sig))
axis('tight')
title('filtriran signal (cheby1)')
subplot(2,2,4)
plot(filter(b3,a3,sig))
axis('tight')
title('filtriran signal (butter)')